#!/usr/bin/bash

PKG_VERSION='1.0'
PKG_MAINTAINER='Your Name <yourname@example.com>'

# Get the directory script is in
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PKG_NAME=$(basename `echo $DIR | sed 's#/workspace##'`)

# Compile
gcc -std=c99 hithere.c -o hithere

# Create package control file
cat > control-file <<EOF
Section: misc
Priority: optional
Standards-Version: 3.6.2

Package: $PKG_NAME
Version: $PKG_VERSION
Maintainer: $PKG_MAINTAINER
# files in /usr/share/doc
Extra-files: README
# files in other directories
Files: hithere /usr/local/bin/hithere
Description: <short description; defaults to some wise words>
 long description and info
  .
   second paragraph
EOF

# Build package
equivs-build control-file
rm control-file
